require(['index-list']);
require(['index-list2']);
require(['index-list3']);
require(['index-tab']);
require(['elevator']);
require(['canvas']);
require(['shoufengqin']);
require(['mainlist']);
require(['detail']);